import configparser
import os
from typing import Any, Dict


def get_config_path() -> str:
    """Get the path to the config.ini file located at the root of the project."""
    return os.path.join(os.path.dirname(os.path.dirname(__file__)), "config.ini")


def get_reddit_api_keys(file_path: str) -> Dict[str, Any]:
    config = configparser.ConfigParser()
    config.read(file_path)
    return config["REDDIT_API"]  # type: ignore


contractions_dict: dict = {
    "aren't": "are not",
    "can't": "cannot",
    "couldn't": "could not",
    "could've": "could have",
    "didn't": "did not",
    "doesn't": "does not",
    "don't": "do not",
    "hadn't": "had not",
    "hasn't": "has not",
    "haven't": "have not",
    "he'd": "he had",
    "he'd've": "he would have",
    "he'll": "he will",
    "he's": "he is",
    "how'd": "how did",
    "how'll": "how will",
    "how's": "how is",
    "I'd": "I had",
    "I'd've": "I would have",
    "I'll": "I will",
    "I'm": "I am",
    "I've": "I have",
    "isn't": "is not",
    "it'd": "it would",
    "it'd've": "it would have",
    "it'll": "it will",
    "it's": "it is",
    "let's": "let us",
    "ma'am": "madam",
    "mightn't": "might not",
    "mightn't've": "might not have",
    "might've": "might have",
    "mustn't": "must not",
    "must've": "must have",
    "needn't": "need not",
    "needn't've": "need not have",
    "o'clock": "of the clock",
    "oughtn't": "ought not",
    "oughtn't've": "ought not have",
    "shan't": "shall not",
    "she'd": "she had",
    "she'd've": "she would have",
    "she'll": "she will",
    "she's": "she is",
    "should've": "should have",
    "shouldn't": "should not",
    "shouldn't've": "should not have",
    "so've": "so have",
    "so's": "so is",
    "that'd": "that would",
    "that'd've": "that would have",
    "that's": "that is",
    "there'd": "there had",
    "there'd've": "there would have",
    "there're": "there are",
    "there's": "there is",
    "they'd": "they had",
    "they'd've": "they would have",
    "they'll": "they will",
    "they're": "they are",
    "they've": "they have",
    "to've": "to have",
    "wasn't": "was not",
    "we'd": "we had",
    "we'd've": "we would have",
    "we'll": "we will",
    "we're": "we are",
    "we've": "we have",
    "weren't": "were not",
    "what'll": "what will",
    "what're": "what are",
    "what's": "what is",
    "what've": "what have",
    "when's": "when is",
    "when've": "when have",
    "where'd": "where did",
    "where's": "where is",
    "where've": "where have",
    "who'd": "who had",
    "who'd've": "who would have",
    "who'll": "who will",
    "who're": "who are",
    "who's": "who is",
    "who've": "who have",
    "why'd": "why did",
    "why'll": "why will",
    "why's": "why is",
    "won't": "will not",
    "wouldn't": "would not",
    "wouldn't've": "would not have",
    "y'all": "you all",
    "y'all'd": "you all would",
    "y'all'd've": "you all would have",
    "y'all're": "you all are",
    "y'all've": "you all have",
    "you'd": "you had",
    "you'd've": "you would have",
    "you'll": "you will",
    "you're": "you are",
    "you've": "you have",
    "ain't": "is not",
    "aren’t": "are not",
    "can’t": "cannot",
    "couldn’t": "could not",
    "didn’t": "did not",
    "doesn’t": "does not",
    "don’t": "do not",
    "hadn’t": "had not",
    "hasn’t": "has not",
    "haven’t": "have not",
    "he’d": "he had",
    "he’ll": "he will",
    "he’s": "he is",
    "i’d": "i had",
    "i’ll": "i will",
    "i’m": "i am",
    "i’ve": "i have",
    "isn’t": "is not",
    "it’s": "it is",
    "it’d": "it would",
    "it’ll": "it will",
    "let’s": "let us",
    "mightn’t": "might not",
    "mustn’t": "must not",
    "shan’t": "shall not",
    "she’d": "she had",
    "she’ll": "she will",
    "she’s": "she is",
    "shouldn’t": "should not",
    "that’s": "that is",
    "there’s": "there is",
    "they’d": "they had",
    "they’ll": "they will",
    "they’re": "they are",
    "they’ve": "they have",
    "we’d": "we had",
    "we’re": "we are",
    "we’ve": "we have",
    "weren’t": "were not",
    "what’ll": "what will",
    "what’re": "what are",
    "what’s": "what is",
    "what’ve": "what have",
    "where’s": "where is",
    "who’d": "who had",
    "who’ll": "who will",
    "who’re": "who are",
    "who’s": "who is",
    "who’ve": "who have",
    "won’t": "will not",
    "wouldn’t": "would not",
    "you’d": "you had",
    "you’ll": "you will",
    "you’re": "you are",
    "you’ve": "you have",
}
